#Award guide when joining the world/server once per player
give_guide = true
show_exclamation_mark_particle = false
#Enables/disables the ability to bonemeal farmland for worms.
enable_worms = true
enable_minigame = true
#Enables/disables fishes caught being unlocked for all online team members.
#Offline players won't be awarded the entry.
enable_ftb_team_sharing = false
#Enables/disables fishes being restricted by seasons.
#Useful if you want to play with a seasons mod but don't like the built-in restrictions.
enable_seasons = true
#Adjusts the vanishing rate multiplier, useful if you want to adjust the fishes' difficulty globally.
# Default: 1.0
# Range: 0.0 ~ 100.0
vanishing_rate_multiplier = 1.0
#Adjusts the moving sweet-spots speed multiplier, useful if you want to adjust the fishes' difficulty globally.
# Default: 1.0
# Range: 0.0 ~ 100.0
moving_speed_multiplier = 1.0
#Adjusts the penalty for missing rate multiplier, useful if you want to adjust the fishes' difficulty globally.
# Default: 1.0
# Range: 0.0 ~ 100.0
penalty_multiplier = 1.0
#Adjusts the fish decay rate multiplier, useful if you want to adjust the fishes' difficulty globally.
# Default: 1.0
# Range: 0.0 ~ 100.0
decay_multiplier = 1.0
#Adjusts the fish decay rate multiplier, useful if you want to adjust the fishes' difficulty globally.
# Default: 1.0
# Range: 0.0 ~ 100.0
pointer_speed_multiplier = 1.0
#Hides entries in the guide book until one has been caught.
hide_entries_until_found = true
