#BBL Core Startup Config
["BBL Core"]
	#Speed that climbable blocks can be climbed, default = 0.15
	"Climbable Block Speed" = 0.15
	#Enable coloring recipes when coloring item are present, eg BBL Colors
	#Uses item names and checks for 'color' in the name, if the item contains a color, coloring items can change it to that color
	"Coloring Recipes in Crafting Tables" = true
	#Enable Void Protection, default = false
	#If enabled, players will be teleported to their spawn point if they fall into the void
	"Enable Void Protection" = false
	#Save the world will try to fix broken world where a block is causing crashes, default = false
	"Try to Save the world" = false
	#X coordinate of block to fix (default = 0)
	x = 0
	#Y coordinate of block to fix (default = 0)
	y = 0
	#Z coordinate of block to fix (default = 0)
	z = 0
